#ifndef ROADTRAFFICSIMULATOR_OPTIMIZATIONALGORITHM_H
#define ROADTRAFFICSIMULATOR_OPTIMIZATIONALGORITHM_H

class OptimizationAlgorithm {
public:
    virtual double run() = 0;
};

#endif //ROADTRAFFICSIMULATOR_OPTIMIZATIONALGORITHM_H
